name: flutter_ayuvani
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:


  fluttertoast: ^7.1.1
  nb_utils:
  shared_preferences: ^0.5.12+2
  google_fonts: 1.1.0
  flutter_vector_icons: 0.2.1
  cached_network_image: ^2.3.1
  flutter_statusbarcolor: 0.2.3
  http_parser: ^3.1.4
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  lipsum: 1.0.1
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.5
  webview_flutter: 
  dio: ^3.0.9
  images_picker:
  google_place:
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  path_provider: ^1.6.24
  flutter_widget_from_html_core: ^0.5.1+4
  keyboard_actions: ^3.3.1+1
  http: ^0.12.2
  firebase_auth: ^0.18.3+1
  firebase_messaging: ^7.0.3
  firebase_core:
  floating_action_bubble: ^1.1.2
  syncfusion_flutter_xlsio:
  syncfusion_officechart: ^18.3.35
  carousel_pro: ^1.0.0
  pdf: ^2.0.0
  flutter_web_browser: ^0.13.0
  edge_detection:
  file_picker: ^2.1.4
  flutter_inappwebview:

  image_pickers: ^1.0.8+7
  receive_sharing_intent: ^1.4.2
  flutter_rating_bar: ^3.2.0+1
  store_redirect: ^1.0.2
  flutter_swiper: ^1.1.6
  printing: ^4.0.0
  stripe_payment: ^1.0.9
  multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  hand_signature: ^0.6.3
  syncfusion_flutter_signaturepad: ^18.4.35-beta
  flutter_image_compress: ^0.7.0
  package_info: ^0.4.0+18
  flutter_tts:
  flutter_markdown: ^0.5.2
  image_picker:
  expandable: ^5.0.1



  #state-managment
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3

  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: OpenSans
       fonts:
         - asset: fonts/OpenSans-Regular.ttf
         - asset: fonts/OpenSans-Bold.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
