class Autogenerated {
  List<CouponData> data;
  String message;
  int status;

  Autogenerated({this.data, this.message, this.status});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = new List<CouponData>();
      json['data'].forEach((v) {
        data.add(new CouponData.fromJson(v));
      });
    }
    message = json['message'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    data['message'] = this.message;
    data['status'] = this.status;
    return data;
  }
}

class CouponData {
  String sId;
  String couponId;
  String promotionId;
  String name;
  String percentOff;
  String customerId;
  String productId;
  String duration;
  int redeemCount;
  String updatedAt;
  String createdAt;
  String isValid;
  String amountOff;

  CouponData(
      {this.sId,
        this.couponId,
        this.promotionId,
        this.name,
        this.percentOff,
        this.customerId,
        this.productId,
        this.duration,
        this.redeemCount,
        this.updatedAt,
        this.createdAt,
        this.isValid});

  CouponData.fromJson(Map<String, dynamic> json) {
    sId = json['_id'];
    couponId = json['coupon_id'];
    promotionId = json['promotion_id'];
    name = json['name'];
    percentOff = json['percent_off'].toString();
    customerId = json['customer_id'];
    productId = json['product_id'];
    duration = json['duration'];
    redeemCount = json['redeem_count'];
    updatedAt = json['updated_at'];
    createdAt = json['created_at'];
    isValid = json['is_valid'];
    amountOff = json['amountOff'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['_id'] = this.sId;
    data['coupon_id'] = this.couponId;
    data['promotion_id'] = this.promotionId;
    data['name'] = this.name;
    data['percent_off'] = this.percentOff;
    data['customer_id'] = this.customerId;
    data['product_id'] = this.productId;
    data['duration'] = this.duration;
    data['redeem_count'] = this.redeemCount;
    data['updated_at'] = this.updatedAt;
    data['created_at'] = this.createdAt;
    data['is_valid'] = this.isValid;
    return data;
  }
}